language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
branches:
  only:
  - master
deploy:
  api_key:
    secure: ohBGbcJY392mlhheTVN9D04OLco9k+3SX+GHtTPnpSN4sUVzOayZVd7I+2pZ2fhCyB6Od/uYklzxkrhxH8yKIeCQYXcZZp/LfHe/lmnR+0tA5+IZj2r1T3RdxYF08CAGmEQOrAu7hVtcxto64QOMBeCTQLS+EZbe3YlVLjTHlq2nMrXPHf/RZ+zyHDmuggjCkw6kzq0gvKAkuyoVW88sKCr7bV9jTsQGYRue7M8NRat8Ieb9+m41wY52YD0TktQ4ef19kIbifGQq5YxtKBjZ+Ud9Gph/p29DADJgAGIqVVI9nOxHvhZnxrZJuQQDpysizHd7S/7YWMk0uZT8lekS9ZMuNgagk6JGkCAMkQLtcH+O/D7OniwWNuTES9XRbiQIJXWhAV35owuNArP45V6X2fmq8usgxROxdHZV3CBN3PLCV24YLj0WWoGQUKiWnMC2wN3WYDpRBEKwhvHGC2Ceju/eDKt/ZgZhUHHy7oMlNXyRjU+aCA9j4pwqJ2k1Ik+VEsJql5YOcZ8+axWAFLTmrM2jQQoRdnlg0Mo3F+Kv8SqER49ESrmpJiCfJv64Q4t3fbOmoGYrkVl9XaeWzKeLk3e+iu9Yx7upAI30udqXnMCL5VNznKLjCzMcCNMfj4ZPYSkzeMXVkhT1XBeGoctJJtn+/51DuYVxHvN6S4QlbHU=
  app:
    master: srecipe-api
  provider: heroku
