language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: eBWdzggrCJTrqmeGsbZSm86FSrombqNTbUJhwNV66lEkoP9Zw7KL7roCJTCRRKEQ1UK2oAm6omw3ZeZUUNirMqS8t1SJIs3peNjTnQBJk6h898OJ4CcwvCsmKabPPVH4o0cQX4DuqsBwnf20FTKOHcgJqRxJ/Dv10eIIRhxe961ucAqfz62chltmBhSbZvo4SWAAdH3HYOhZm/r2HItjdPHBpN+mxm1n9u/yA8hkCMZfkytE2uPnTm648AIpq1p96cglgOWE7fIBd7Y8MYBwA6xrsKrpVV2eg0DRhft7NzNZP21bgI33+kJ/MHDA27qt1dXMXN4oVpNGuxWKTbMe3Kp7DypRmms/MepP64wsjyjiUueSu8eeXBaC70/84LtntyOLOfwVRQ76g61+4RV69EPBsbCa8SKeTUBhnl5hY/L6Em0oMSSlM2qkhNC3RbtbGSHlENN25accvq94ILV3B1Rku1xytwdhZN6FnD6crxjVpQ/QC2GnslRa1K+yhKENUbEvvILVCiyKw7iJWYYbewY3+tP0tDCM19gnuM5X4t/qYNM+3S9N4gHGw8sTogjmkWbfRs8XnGRYEJFSEto7EE4J0IoFy1z6HLUKB7P1O95ycS8OxGbzPb7JTieygSTavRRAPMlzRVi5RN1Hr3LRsfdbga5w7qHdH3IJOCw69yk=
  app: srecipe-api
  on:
    repo: JohnnyAir/simple-recipe-api
